#format and mount volume
- name: Format Volume
  become: yes
  filesystem:
    fstype: ext4
    dev: /dev/vdc

- name: Create Mount Dir
  become: yes
  file:
    path: /mnt/demo
    state: directory

- name: Mount Volume
  become: yes
  mount:
    path: /mnt/demo
    src: /dev/vdc
    fstype: ext4
    state: mounted
#install software
- name: Install curl
  become: yes
  apt:
    name: curl
    update_cache: yes
    state: latest

- name: Install Maven
  become: yes
  apt:
    name: maven 
    state: latest

- name: Install OpenJDK
  become: yes
  apt:
    name: openjdk-8-jdk
    state: latest


- name: Install Docker
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - docker.io

- name: Install Git
  become: yes
  apt:
    name: git 
    state: latest

- name: Clone Git Repo
  become: yes
  git:
    repo: https://github.com/Serena-Chenzz/Walkability.git
    dest: /home/ubuntu/Walkability

- name: execute maven project
  shell: "{{item}}"
  args:
    chdir: /home/ubuntu/Walkability
  with_items:
    - sudo mvn clean
    - sudo mvn compile
    - sudo mvn test

